package com.teaagent.domain.firemasedbEntities.enums.stockEntry

enum class SLLevel {
    SELECT, IMMEDIATE,LEVEL_OVER_LEVEL, INTERMEDIATE_TIME_ZONE, HIGHER_TIME_ZONE

/*
    SELECT, IMMEDIATE_EXECUTION_ZONE,LEVEL_OVER_LEVEL_EXECUTION_ZONE, INTERMEDIATE_TIME_ZONE, HIGHER_TIME_ZONE
*/
}