package com.teaagent.domain.firemasedbEntities.enums.stockEntry
enum class TradeIncomeType {
//        SELECT, MONTHLY, WEEKLY, DAILY, HOURLY,PORTFOLIO_1,PORTFOLIO_2
SELECT, ANDROID_SG, ANDROID_UK, ANDROID_GERMANY, ANDROID_DUBAI,ANDROID_INDIA,MBA_UK,MBA_CANADA,MBA_US,MBA_SG,MBA_INDIA

}